version: "3.9"

services:

  stormbian:
    image: jamesstorm/stormbian
    container_name: ${APPNAME} 
    hostname: ${APPNAME}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - ${PORT}:22
    volumes:
      - ${APPDATA}:/appdata
    restart: always
    tty: true

    
